is_even = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
merkleProof = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nullifier = ""
nullifier_hash = ""
recipient = ""
root = ""
secret = ""
